### ISSUE TITLE
code crashing - with log

### ISSUE THREAD

**Issue by matanfih** [SaoYan/LearnToPayAttention#6]
python train.py --attn_mode before --outf logs_before --normalize_attn --log_images

loading the dataset ...

Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to CIFAR100_data/cifar-100-python.tar.gz
100.0%Extracting CIFAR100_data/cifar-100-python.tar.gz to CIFAR100_data
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    main()
  File "train.py", line 51, in main
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=opt.batch_size, shuffle=True, num_workers=8, worker_init_fn=_init_fn)
NameError: name '_init_fn' is not defined

**Comment by SaoYan** [comment]
Fixed
