### ISSUE TITLE
model1.py same as model2.py

### ISSUE THREAD

**Issue by fatalfeel** [SaoYan/LearnToPayAttention#7]
model1.py
x = self.conv_block1(x)
x = self.conv_block2(x)
l1 = self.conv_block3(x) # /1
x = tnf.max_pool2d(l1, kernel_size=2, stride=2, padding=0) # /2
l2 = self.conv_block4(x) # /2
x = tnf.max_pool2d(l2, kernel_size=2, stride=2, padding=0) # /4
l3 = self.conv_block5(x) # /4
x = tnf.max_pool2d(l3, kernel_size=2, stride=2, padding=0) # /8
x = self.conv_block6(x) # /32
g = self.dense(x) # batch_sizex512x1x1
###can modify as
x = self.conv_block1(x)
x = self.conv_block2(x)

l1 = self.conv_block3(x) # /1
l1 = tnf.max_pool2d(l1, kernel_size=2, stride=2, padding=0) # /2

l2 = self.conv_block4(l1) # /2
l2 = tnf.max_pool2d(l2, kernel_size=2, stride=2, padding=0) # /4

l3 = self.conv_block5(l2) # /4
x  = tnf.max_pool2d(l3, kernel_size=2, stride=2, padding=0) # /8

x = self.conv_block6(x) # /32
g = self.dense(x) # batch_sizex512x1x1
##################################################3
model2.py
x = self.conv_block1(x)
x = self.conv_block2(x)
x = self.conv_block3(x)
l1 = tnf.max_pool2d(x, kernel_size=2, stride=2, padding=0) # /2
l2 = tnf.max_pool2d(self.conv_block4(l1), kernel_size=2, stride=2, padding=0) # /4
l3 = tnf.max_pool2d(self.conv_block5(l2), kernel_size=2, stride=2, padding=0) # /8
x = self.conv_block6(l3) # /32
g = self.dense(x) # batch_sizex512x1x1
###can modify to
x = self.conv_block1(x)
x = self.conv_block2(x)

l1 = self.conv_block3(x) # /1
l1 = tnf.max_pool2d(l1, kernel_size=2, stride=2, padding=0) # /2

l2 = self.conv_block4(l1) # /2
l2 = tnf.max_pool2d(l2, kernel_size=2, stride=2, padding=0) # /4

l3 = self.conv_block5(l2) # /4
x  = tnf.max_pool2d(l3, kernel_size=2, stride=2, padding=0) # /8

x = self.conv_block6(x) # /32
g = self.dense(x) # batch_sizex512x1x1

they are the same~~~~

**Comment by SaoYan** [comment]
Backbone network is the same; attention is not same.
Model 1 applies attention before max-pooling; attention applies after max-pooling
